export const dummyCategory = [
  { Id: 'www', title: 'Work', bgColor: '#FFA801' },
  { Id: 'sss', title: 'Shopping', bgColor: '#575FCF' },
];

export const dummyList = [
  {
    id: 'w01',
    contents: 'Call to Elon Musk',
    star: true,
    complete: false,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w02',
    contents: 'Zoom with client',
    star: true,
    complete: false,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w03',
    contents: 'Meeting with designers',
    star: true,
    complete: false,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w04',
    contents: 'Lunch with Boss',
    star: false,
    complete: false,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w05',
    contents: 'Submit expenses',
    star: false,
    complete: false,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w06',
    contents: 'Book flight ticket',
    star: false,
    complete: false,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w07',
    contents: 'Finish weekly report',
    star: false,
    complete: false,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w08',
    contents: 'Clean my desk',
    star: false,
    complete: true,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w09',
    contents: 'Submit expenses',
    star: false,
    complete: true,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w10',
    contents: 'Book flight ticket',
    star: false,
    complete: true,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w11',
    contents: 'Finish weekly report',
    star: false,
    complete: true,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w12',
    contents: 'Clean my desk',
    star: false,
    complete: true,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w13',
    contents: 'Clean my desk',
    star: false,
    complete: true,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w14',
    contents: 'Submit expenses',
    star: false,
    complete: true,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w15',
    contents: 'Book flight ticket',
    star: false,
    complete: true,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w16',
    contents: 'Finish weekly report',
    star: false,
    complete: true,
    category: 'Work',
    bgColor: '#FFA801',
  },
  {
    id: 'w17',
    contents: 'Clean my desk',
    star: false,
    complete: true,
    category: 'Work',
    bgColor: '#FFA801',
  },

  {
    id: 's01',
    contents: 'Call to Elon Musk',
    star: false,
    complete: false,
    category: 'Shopping',
    bgColor: '#575FCF',
  },
  {
    id: 's02',
    contents: 'Zoom with client',
    star: false,
    complete: false,
    category: 'Shopping',
    bgColor: '#575FCF',
  },
  {
    id: 's03',
    contents: 'Meeting with designers',
    star: false,
    complete: false,
    category: 'Shopping',
    bgColor: '#575FCF',
  },
  {
    id: 's04',
    contents: 'Lunch with Boss',
    star: false,
    complete: false,
    category: 'Shopping',
    bgColor: '#575FCF',
  },
  {
    id: 's05',
    contents: 'Submit expenses',
    star: false,
    complete: false,
    category: 'Shopping',
    bgColor: '#575FCF',
  },
  {
    id: 's06',
    contents: 'Book flight ticket',
    star: false,
    complete: false,
    category: 'Shopping',
    bgColor: '#575FCF',
  },
  {
    id: 's07',
    contents: 'Finish weekly report',
    star: false,
    complete: true,
    category: 'Shopping',
    bgColor: '#575FCF',
  },
  {
    id: 's08',
    contents: 'Clean my desk',
    star: false,
    complete: true,
    category: 'Shopping',
    bgColor: '#575FCF',
  },
];
